### PR TITLE
fix: remove control operator & in commands of systemd units

### PR DESCRIPTION
**Pull request by holishing**
for it will cause error when systemd service is starting.

### CODE REVIEW

**Comment by IepIweidieng** [comment]
`&` means "to run a command in the background", but why does it cause errors? Might you be willing to explain the issue in more detail? E.g., what kind of error occurred? Syntactic one or runtime one?

Might you even bother to share how you came up with this solution?

**Comment by holishing** [comment]
ok, I will check the manual and explain it later.

Wei-Cheng Yeh (IID) ***@***.***>於 2021年10月30日 週六，下午6:21寫道：

**Comment by holishing** [comment]
https://www.freedesktop.org/software/systemd/man/systemd.service.html#Command%20lines
Here says: " only the meta-characters and expansions described in the following paragraphs are understood, and the expansion of variables is different. Specifically, redirection using "<", "<<", ">", and ">>", pipes using "|", running programs in the background using "&", and *other elements of shell syntax are not supported.*"

So I misused it before.

**Comment by IepIweidieng** [comment]
Would you mind to also summarize it in the commit message?

**Comment by IepIweidieng** [comment]
LGTM.

**Review by IepIweidieng — APPROVED** [review]

**Pull request merged**
